# Generated by Django 5.0.6 on 2026-07-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_lessonappointment_decline_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceappointment',
            name='event_type',
            field=models.CharField(choices=[('Cultural Program', 'Cultural Program'), ('School Program', 'School Program'), ('Festival', 'Festival'), ('Community Event', 'Community Event'), ('Traditional Ceremony', 'Traditional Ceremony'), ('Workshop', 'Workshop'), ('Lecture-Demonstration', 'Lecture-Demonstration'), ('Music Lesson', 'Music Lesson'), ('Private Event', 'Private Event'), ('Other', 'Other')], default='Concert', max_length=100),
        ),
    ]
